# Generated by Django 3.2.4 on 2021-07-29 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='antecedentes_pacientes',
            old_name='enfermedadCardiovascular',
            new_name='enfermedad_cardiovascular',
        ),
        migrations.RenameField(
            model_name='antecedentes_pacientes',
            old_name='otraComplicacion',
            new_name='otra_complicacion',
        ),
        migrations.RenameField(
            model_name='informacion_medica',
            old_name='entidadUnidadMedica',
            new_name='entidad_unidad_medica',
        ),
        migrations.RenameField(
            model_name='informacion_medica',
            old_name='resultadoAntigeno',
            new_name='resultado_antigeno',
        ),
        migrations.RenameField(
            model_name='informacion_medica',
            old_name='resultadoLaboratorio',
            new_name='resultado_laboratorio',
        ),
        migrations.RenameField(
            model_name='informacion_medica',
            old_name='tomaMuestraAntigeno',
            new_name='toma_muestra_antigeno',
        ),
        migrations.RenameField(
            model_name='informacion_medica',
            old_name='tomaMuestraLaboratorio',
            new_name='toma_muestra_laboratorio',
        ),
    ]
