# Generated by Django 3.2.4 on 2021-07-29 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0002_auto_20210729_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='antecedentes_pacientes',
            name='id',
        ),
        migrations.RemoveField(
            model_name='informacion_medica',
            name='id',
        ),
        migrations.AlterField(
            model_name='antecedentes_pacientes',
            name='ID',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, unique=True, verbose_name='ID_caso'),
        ),
        migrations.AlterField(
            model_name='informacion_medica',
            name='ID',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, unique=True, verbose_name='ID_caso'),
        ),
    ]
